name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js (v${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run coverage

      - name: Publish coverage
        uses: codecov/codecov-action@v2
        if: ${{ matrix.node-version == 14 }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/clover.xml
          fail_ci_if_error: true